### ISSUE TITLE
Scrolling become stuttery with hints showing in Firefox

### ISSUE THREAD

**Issue by jamesmugford** [david-tejada/rango#154]
It's especially noticeable when smooth scrolling.

Chrome is excellent.

**Comment by ghost** [comment]
I'm also using firefox, but can't reproduce

**Comment by david-tejada** [comment]
Does it happen on all pages? Do you use smooth scrolling? It might be related to #103

**Comment by jamesmugford** [comment]
Yes, it happens on all pages, e.g. when using Wheel Downer or Wheel Gaze command.

It also happened when using other smooth scrolling software applications, that I have tried (KinesicMouse).

Using the hardware mouse middle click "auto scroll" is fine.

It looks like an event is firing much more frequently whilst using software to scroll, which causes a massive surge in CPU usage. I have a fairly beefy CPU (9700k), with plenty of RAM, and plenty of headroom whilst testing.

The issue happens even in private tabs with only Rango enabled.

**Comment by david-tejada** [comment]
Ok, I thought it was related to Rango's own scrolling. It might be a performance issue, I could see if I could improve it so this doesn't happen. Would you mind recording a profile while this happens? You just have to install the profiler button, click to start, do some scrolling that reproduces the issue and then click again to stop. Then you have to send me the link to the profile page.

https://profiler.firefox.com/

**Comment by david-tejada** [comment]
You might have to upload the local profile first

**Comment by david-tejada** [comment]
Thinking about this some more, if it happens on all pages it can't be a performance issue. It could be on some pages that load many dom elements as you scroll. But if it happens on some page like Wikipedia this can't be a performance issue because in a page like that Rango uses very little resources.

I don't use `wheel downer` much but I have tried now and to me it looks stuttery in all the browsers, with or without Rango on. Here are a couple of recordings, first with Rango disabled and then enabled:

## With Rango disabled
![wheel-downer](https://github.com/david-tejada/rango/assets/3219671/944f4d2c-381d-4199-8d96-17dbed123eb8)

## With Rango enabled
![wheel-downer-with-rango](https://github.com/david-tejada/rango/assets/3219671/63a516f7-680c-4200-99ec-b132a7c317da)

If you could record a profile I could check to see if there's something else going on.

**Comment by david-tejada** [comment]
Closing this issued due to inactivity add inability to reproduce the issue.
