### ISSUE TITLE
Feature Request: Add 'exclude all' command that excludes every hint on a page.

### ISSUE THREAD

**Issue by swissmas** [david-tejada/rango#183]
I want to be able to have a very small amount of custom hints on certain pages. In order to do this now, on pages with a large amount of hints I need to spend a lot of time excluding hints. It would be easier if their were an 'exclude all' command that automatically excluded every hint on the page, that way I can save time by just including the few hints I do want instead of having to exclude the large majority of hints I don't want.

**Comment by david-tejada** [comment]
This is something I thought about when implementing custom hints but I wasn't sure if there was the need for it.

I need to think about the workflow and what happens when an element matches both an include and exclude selector, because I think now exclusion wins. So excluding all and then including some would still leave no hints.
