### ISSUE TITLE
"press <key>" gets recognized as "pre <user.rango_target>" too frequently

### ISSUE THREAD

**Issue by jmegner** [david-tejada/rango#187]
About once a day, I say "press crunch" and it gets recognized as "pre crunch", which is not what I want.  I am guessing this affects other people as well.

I have changed the talon rules to `rango pre/post <user.rango_target>` to prevent the misrecognition.

The best I can tell, pre/post commands help take you to the beginning or end of a text field, which I am guessing is used far less than "press <key>". Can we name them something else or have some prefix word?

Prefixes: jump, go, rango.

Alternate names: head, tail, start, finish.

**Comment by david-tejada** [comment]
I use `pre` and `post` quite frequently. Mainly after doing some search with `google hunt` or similar and wanting to correct words in one go. I probably use those more than `press`. I have had misrecognitions between `press` and `pre` here and there but it's not a big issue for me.

I cannot simply remove a command. People who are used to `pre` or `post` won't know why those commands don't work anymore all of a sudden. It also aligns with Cursorless so it's less mental load for people that use both.

Changing the commands in rango.talon is okay. I try to make changes so that it minimizes possible merge conflicts.

If this happens to you on YouTube you could also create custom commands for that:

```talon
tag: browser
browser.host: /youtube/
-
play|pause: key(k)
```
