### ISSUE TITLE
Feature Request: Ability to store multiple scroll positions within a webpage

### ISSUE THREAD

**Issue by SandeepJoel** [david-tejada/rango#193]
Rango needs to provide options to store multiple scroll positions within a webpage. So that we can quickly move between parts of a huge web page. Basically like bookmark vcode functionality inside chrome tabs ?  (like vimium chrome extension’s mark functionality)

**Comment by david-tejada** [comment]
Since you mentioned in the Slack channel that you might want to attempt this I have outlined here the rough steps to accomplish it. If you get stuck and need help let me know:

- Create the commands in rango-talon. You will have to create a different PR in that repository.
- Add the commands type in *typings/RangoAction.ts*.
- Add the actions in *content/actions/runRangoActionWithoutTarget.ts*. From those cases you probably need to call the functions `storeScrollMark` and `scrollToMark` or something along those lines that you will have to implement in *content/actions/scroll.ts*.
- In *scroll.ts* you probably need to use `getScrollableAtCenter` or the commands will only work when the whole page scrolls, which isn't always the case.
- You will need to store the scroll positions in a map. Something like this, with the first string key being the url and the inner one being the letter and the corresponding scroll position:
    ```typescript
    customScrollMarks: Map<string, Map<string, number>>
    ```
  You need to define this type in *typings/StorageSchema.ts* and give it an initial value in *common/settings.ts*. In order to store and retrieve this map you need to make use of the utility functions `store` and `retrieve` defined in *common/storage.ts*.
- I let you figure out how to actually get the scroll position and scroll to it. You probably need to use `scrollTop` and the method `scrollTo`.

**Comment by C-Loftus** [comment]
I was thinking of implementing similar behavior (storing unique hints), but for the purpose of scripting.   ( For instance, a user could say a command like `mark air bat as input` ) and then use a command to scroll/manipulate `input` where `input` refers to the syntactic name of a hint.
Described here: #190 

@SandeepJoel , should we try and coordinate on this? I think there will be some shared functionality related to saving a hint.  perhaps it would be good to  come to a consensus regarding the best way of saving a hint, and merge that first?   I wanted to make sure that we don't have two ways of saving hints, one for scrolling and one for scripting. 
 
  
 @david-tejada wasn't sure if you have any opinions on how do you want marks to be saved such that they are also exposed to users. 

I am not sure if this is an anti-pattern based on how rango is designed, but I was almost thinking of storing marks (at least for scripting) locally in a JSON file ( assuming it is okay for rango to send an element ID back to Talon over the clipboard and it isn't just one way). That way it is easier to copy and view the mark names when a user is writing scripts locally

 I was thinking of having the command be something like
`mark <hint> as <word>` . So saying `save air bat as input` (where `air bat` refers to the input box on slack) could return an updated json with values like the following. Then the user could write a talon script using "input" as one of the input parameters. 
```
{
    "websites": [
        {
            "slack": {
                "input": "DIV_ID_NAME_GOTTEN_FROM_RANGO"
            }
        }
    ]
}
```
With regards to scrolling,  we could probably just create a dynamic scope in a Talon file, created from that json,  instead of needing to save it internally to the extension and obscure it from the user. ( I think we are going to need to have away to export it anyways given the fact that users are likely to switch setups and want to keep their saved marks)

 I suppose I'm just thinking that if we don't save it locally then it is going to be difficult for people to track lots of marks unless we create another page for this which seems like unnecessary work currently.

**Comment by david-tejada** [comment]
The marks in this issue (scrolling) aren't relative to hints so there's no need to reference or store hints. I will answer in your issue about the rest to keep things focused

**Comment by C-Loftus** [comment]
Ah ok that makes sense, I suppose I misinterpreted the use of the word mark here
