### ISSUE TITLE
After reopening firefox, two tabs had the same letter/marker

### ISSUE THREAD

**Issue by maxbruening** [david-tejada/rango#195]
When I reopened firefox, two tabs were assigned the same letter/marker. There is already code that is supposed to prevent this, but apparently it does not work in firefox. See the slack message from today.

**Comment by david-tejada** [comment]
I think I found the issue. The problem was that I was using the "unloaded" status of the tabs, which apparently is just a Chrome thing, Firefox just mark them as "complete".

I found a fix although I couldn't test properly because there's no easy way to test it as temporary extensions are removed when you relaunch Firefox. I have tested in Chrome and it works fine and I don't see any reason it shouldn't work in Firefox.

I'll see if I can make a release soon with this and a couple of other minor fixes.
