### ISSUE TITLE
Individual colors for each letter

### ISSUE THREAD

**Issue by runar-rkmedia** [david-tejada/rango#210]
To make it easier to visually identify each word, it would be beneficial if each letter was their own color. 

For instance, the letter 'a' is blue, 'b' is red, 'c' is teal and so.

Perhaps it is better to change the background and text/color for each letter.

**Comment by bacall213** [comment]
User choice is good, but changing the color of each letter poses a few potential issues for accessibility. WCAG 2.1 specifies that the [contrast for small text should be at least 4.5:1](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html). Rango already ensures user adjustable high contrast by adapting the hint colors according to the background it's sitting on top of (it's really quite neat how it does it, too).  The other aspect of this is that various [color blind ](https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/color-blindness/types-color-vision-deficiency) adjustments would need to be added to ensure the colors that are chosen aren't going to make the letters invisible if the user is, as an example, blue/green, purple/red, and yellow/pink colorblind (tritanopia). This is usually done through a menu in the tool settings where the user chooses the specific color blind adjustment needed.

Adding different colors for each letter and/or the background would mean also adjusting it on the fly so that the text has sufficient contrast against the background color and the background on the page. For a page with a lot of hints, that could be a lot of additional client side calculation needed to render the hints. 

It might work out nicely if this was an optional rendering style provided via a toggle in the options menu though.

Just a few things to consider.

**Comment by david-tejada** [comment]
Do you have any issues identifying the letters of the hints? There are a lot of settings you can customize to make it easier for you:

- Use uppercase letters.
- Use bold letters.
- Increase the size of the hints.
- Change the font family.
- Require a minimum contrast ratio.
- Change the background and font colors so they are constant.

I don't see how changing the color of each individual letter is going to make it easier for you to identify them. And for that I would have to make the background color constant (white, probably) and find 26 colors that have good contrast with white, that are distinctive enough between them and that take into consideration all the things mentioned by @bacall213.

**Comment by david-tejada** [comment]
Closing this one due to the inactivity and the impracticality of the proposed feature.
