### ISSUE TITLE
go to next tab playing audio / mute tab commands

### ISSUE THREAD

**Issue by timo** [david-tejada/rango#246]
things i can think of

* go to the next tab that has audio
  * either skip muted tabs, or also go to muted tabs
* mute the current tab / tab by letter / next tab that's playing audio
* if possible, also make tabs that recently played audio targetable (for example if there was a notification sound you're unfamiliar with, and if it's short you can easily miss the time when it still shows the icon)

**Comment by david-tejada** [comment]
I am going to start working on this. I think everything you mentioned is doable. This is a draft of the commands and what each will do. For the mute/unmute commands I'm unsure if it's better to have two commands or just a command that switches the mute/unmute state. Let me know what you think and if there's something you'd like to be added.

- `go playing`: Go to the next tab that has audio (muted or not).
- `go sound`: Go to the next tab that has audio and is not muted.
- `go muted`: Go to the next muted tab.
- `go last sound`: Go to the tab that most recently started (it might have already stopped) playing audio.

- `mute/unmute current`: Mute/unmute the current tab.
- `mute/unmute next`: Mute/unmute the next tab that's playing audio and is not already muted/unmuted.
- `mute/unmute <target>`: Mute/unmute a tab by letters.

**Comment by david-tejada** [comment]
In Firefox is not possible to know if a muted tab has audio because of this bug: [1667585 - WebExtensions API tab type: audible property incorrect when tab is muted](https://bugzilla.mozilla.org/show_bug.cgi?id=1667585)

I think `go muted` should go to the next muted tab that has audio playing. Because of the aforementioned bug this is not possible in Firefox. I think for the time being I will make `go muted` go to the next muted tab, regardless of if it has audio or not.

On the other hand I will make `go playing` go to the next tab that has `audible` set to `true`. This will make its behavior as intended in Chrome but in Firefox will ignore all tabs that are muted.
