### ISSUE TITLE
rango renames bookmarks to current tab title

### ISSUE THREAD

**Issue by gpunktschmitz** [david-tejada/rango#252]
steps to reproduce:

1. enable rango
2. open "google.com" and add it to the bookmark toolbar
3. open new tab and go to "github.com"
4. while "github.com" beeing active edit the bookmark "google.com" which was just created
5. enter anything as new title
6. the result is that the title of the current tab "github.com" will be used as bookmark title

**Comment by david-tejada** [comment]
Oh, this is bad. I see why this is happening. I think I can prevent this if I make sure that the current url matches that of the bookmark and the title without decorations contains the title of the bookmark. I'll see if I can fix it soon and make a release.

**Comment by gpunktschmitz** [comment]
I for one add links to the bookmarks toolbar and remove (to only have the favicons) or rename the title for beeing shorter. 
Don't know how to but maybe only "intercept" if the bookmark is added, but not if it is updated?

**Comment by david-tejada** [comment]
I need to use the onChange event too because of the way bookmarks are saved in Chrome.  When the bookmark popup appears the bookmark is saved. We change the title after onCreated is triggered, but when the user hits "done" the title of the bookmark will be changed again to the value of the input field of the popup window.

I think the solution I have come up with is robust and I don't think we'll have any more issues.
