### ISSUE TITLE
rango adds new lines to pad

### ISSUE THREAD

**Issue by gpunktschmitz** [david-tejada/rango#264]
I opened a link to a pad and noticed rango adding new lines on every refresh

example page: https://pad.cogneon.io/p/asdf

**Comment by david-tejada** [comment]
It looks like every time you insert something it tries to wrap it in a `div` or a `span`. It looks it like it's constantly checking for any changes in the line where the cursor is and the lines before and after. When it finds something that isn't wrapped it tries to wrap it. Since it can't wrap the hints in a span it looks like for wherever reason the behavior is to insert a new line. Strange.

I can't it place the hints elsewhere since the whole body is contenteditable. The only solution I can think of is to just not show hints for this iframe. You would still get hints in the toolbar.

For the time being you can do this to make this page usable:
- Include all the hints in the tool bar. Make sure all the hints are green before using `custom hints save`.
- Exclude all the hints with `exclude all` and then `custom hints save`.
