### ISSUE TITLE
Marks do not persist

### ISSUE THREAD

**Issue by BoltonBailey** [david-tejada/rango#266]
I was trying to add a mark for the "Files Changed" tab on a Github PR page.
<img width="703" alt="Screenshot 2024-01-18 at 4 13 50 AM" src="https://github.com/david-tejada/rango/assets/8030599/a0b5a030-3f34-49d9-a309-05ef17a951a9">

Unfortunately, when I navigate to a new PR, "mark show" indicates the mark is not there anymore. Perhaps this might be due to some subtle difference in the element? It would be nice if elements like this kept their marks.

Even better, it would be nice if link elements had the same property that tabs do where you can say "tab hunt phrase" and it will fuzzy search for a tab matching that phrase. If I could just say something like "click link hunt phrase" and have it fuzzy search over the text components of links, then I could do away with marks altogether (and maybe even turn off hints and navigate solely by speaking the text of the links I want to click).

**Comment by david-tejada** [comment]
The reason the marks don't persist here is because the unique selector is created making use of the href of the link, which changes for every PR. I'm going to go ahead and blacklist hrefs when creating unique selectors since they are clearly problematic in situations like this.

Would you mind opening another issue for the fuzzy link search part? You can just copy the second paragraph and link to this issue if you want. I will see if I can implement something when I have some time.

**Comment by BoltonBailey** [comment]
Ok thanks will do!
