### ISSUE TITLE
Support targets where click event was added with addEventListener

### ISSUE THREAD

**Issue by AndreasArvidsson** [david-tejada/rango#37]
Example of this is `view replies` for 9gag comments

Possible solutions 
https://stackoverflow.com/questions/9046741/get-event-listeners-attached-to-node-using-addeventlistener

**Comment by david-tejada** [comment]
I got this working on the branch https://github.com/david-tejada/rango/tree/get-event-listeners, but I don't think I'm gonna merge it into main. It turns out libraries like jQuery or React don't register events to individual elements, they register an event of each type they use for the whole document and then use event delegation using the target property of the event. So after all the functionality is not very useful. I've done some tests and in the only place where it found additional hints was in that 9gag `view replies` button and I can get that clickable easier by just checking `window.getComputedStyle(element).cursor === "pointer"`, checking also that the parent doesn't also have a pointer cursor and that there are not close descendants that are clickable.

I am closing this issue for now and we can reopen it in the future if we find that it would be of use in some pages.

**Comment by david-tejada** [comment]
I forgot to mention the reason I just don't add the code is for performance reasons. The code doesn't spend a lot of resources but it's something and taking into account how little we gain from it, it doesn't seem to be worth it.
