### ISSUE TITLE
Documentation/changes for how Rango decides what to hint

### ISSUE THREAD

**Issue by adam-coster** [david-tejada/rango#64]
There are a handful of websites that don't have all of the hints I need. Some are in my control and some aren't. Regarding modifying the hinting targets:

- **Request:** Can you add info to the docs about how Rango decides where hints should go? I could use that to make updates to sites I control, and to guide feature requests for websites I don't control.
- **Question:** Is there some way I can customize Rango's logic for where it adds hints, per website? For cases where I can't control a given website it would be nice to be able to change how Rango behaves on that site.

**Comment by david-tejada** [comment]
The logic for deciding what is clickable is here https://github.com/david-tejada/rango/blob/main/src/content/utils/getClickableType.ts. If something that is clickable doesn't receive a hint it can be because it uses a non semantic element and has an event attached with addEventListener. You can read more about it in #37. I will add documentation explaining this. It would be useful if you send me the links so I can check why these elements aren't receiving hints.

I'm planning on adding a context menu item so that users can mark something as clickable for a given website. I will need to add some logic to also give hints to similar elements, probably using class and ancestor topology. I will need to make some tests to see what works best.

**Comment by adam-coster** [comment]
I see, so if I'm understanding correctly the design of Rango is to hint specifically in interactive elements. I was expecting it to also label non-interactive landmarks so that I could use those as scroll positions, e.g. to scroll to a header or even paragraph.

Is hinting non interactive landmark elements outside of scope? In order of precedence, the non-interactive semantic elements that seem like they'd be useful are:

- heading
- section
- main
- article
- nav
- paragraph

Though headings alone would probably be sufficient.

Regarding the site in question, I use favro.com for project management. It has boards with cards (like a lot of project management software), but terrible non-semantic markup (just divs without roles, aria labels, or even human-friendly classes). I'd like to submit a feature request for them to improve the accessibility via semantic markup, but I'm assuming I need to suggest whatever minimal changes could be made to make them more likely. In the absence of a Rango feature for adding custom selectors, probably asking them to add some role attributes is the best move.

**Comment by adam-coster** [comment]
Regarding customization: given the huge range in how people use markup (and how little of it even tries to be semantic), and how much that can change over time, being able to use CSS selectors to both add and remove hint locations would be super useful. Letting the user put in a selector is not as accessible as your suggested, automatic mechanism of "hint things like this", but it would be a lot easier to implement and would serve as a nice bridge. Plus, Talon users seem to be quite tech-savvy on average so I suspect a substantial fraction of Talon users would be able to make use of the custom-selector approach.

In the case of `favro.com`, for example, there are enough human-friendly class names that it would be easy to select a huge fraction of the currently-non-hinted elements.

If it were easy to add those to this repo, then people could even make PRs for popular sites. Though I imagine you'd want to minimize how many sites have their selectors stored here so that you don't have to maintain them.

**Comment by david-tejada** [comment]
Yes, originally there weren't any scroll commands so there wasn't much sense in adding those as landmarks. But I agree it could be useful for scrolling. I'll have to try and see how that results. As it is now some pages are clogged with hints and adding all those elements could make it worse. Maybe I could have that under a setting. Then there's the fact that users expect elements that have hints to be clickable so it could be confusing. Ultimately the goal is to have cursorless-style hats which will be much better suited to act as landmarks.

Yes, probably adding a context menu with something like "Mark elements with class .some-example-class as hintable" could be a good start. That's easy to implement and would allow me to gather feedback and see if people need something more.

The idea of having custom code for popular sites is also interesting. I'll start with adding the context menu and we'll go from there.

**Comment by adam-coster** [comment]
That all makes sense!

While automatically pulling the option up via context menu would work for some cases, people's approaches to classing elements is so varied that I worry it'll be a hopeless fight against edge cases. I imagine fully manual would be the easiest to implement, and would let people experiment with the idea to give feedback.

In the Favro.com case:

- All cards have `class="group-row js-group-row js-nav-to js-boarditem js-tap-hold-drag js-tap-indication ui-sortable-handle"`, so pulling up that selector automatically _would_ work.
- All clickable cells have something like `class="cell layout-h cell-members table-9e5e9f4176c55b3b6bfa142e-members js-cell"`, where that long hash-thingy is unique to every cell. It would be pretty easy for me to inspect the page to come up with the selectors that would get the job done, but very hard to automatically discover a selector.

Similarly, being able to select *against* things that are already hinted would also be very useful. On the point of things getting cluttered, the GitHub home page has a lot of noise due to having lots of duplicate links:

![github-rango-example](https://user-images.githubusercontent.com/28758057/182042094-7b00a13b-97c6-4e70-a41a-f3882f72012c.png)

In the screencap, you can see that in the sidebar half of the hints are redundant (the icon and the repo name are both linked to the same URL for each repo). Similarly, in the "For You" page we could drop `r`, and `s`, etc. The notifications page has a similar degree of noise -- each checkbox is flagged with two hint labels.

This would again be pretty straightforward with manual inspection and a custom selector, but hard to match to a general pattern.

This is a hard problem, and I can see why you're favoring switching over to the Cursorless approach! Since that would be an enormous change I'm wondering if, in the interim, providing a very manual selector-based approach would be sufficient. I'm thinking something like the following:

Move *all* selection into editable selectors. For example, the current list of roles and element types could be converted into selectors and be the default list of selectors. This would also let you reduce the code logic, since you can use the built-in [`Element.matches()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches) JavaScript function in place of some or all of your current filtering logic. That would let you store selectors separately from the logic, which would also make it easier for you and contributors to add per-site selector lists without having to dive into complex code logic.

There's of course still the problem of how you determine how to map the list of selectors onto a given site, since they might apply across the host or only to subsets of pages. I'd be very happy with a solution where:

- There was a general Rango extension settings page I could go to
- That page included a "Hint Overrides" section
- Each Override consisted of
  - A text input to provide a pattern for matching the host
  - A textarea for selectors, one per line
- I could click an "Add Override" to get a new Override form
- The selectors would be prepopulated to the default ones
- On navigation, Rango compares the new URL to the Overrides, grabs all of the ones that match, and then uses those to select hints. (If none are found, it just uses the default selectors.)

In the absence of being able to do that as an extension user, being able to submit a PR with custom selectors for a given site would also be solid.

Finally, I want to make sure I say that truly appreciate all the work you've done with Rango and totally understand if you don't want to take it in this direction 😀. Thanks for taking the time to read my jumble of thoughts!

**Comment by david-tejada** [comment]
Thanks for the comprehensive comment. I appreciate the input.

I agree on every point and you are right that automatically getting class names it's going to get complicated. I still like the ease of use of a context menu though, so I'm thinking that a solution could be to have both: a way to add selectors to include/ignore in the settings and a context menu item to select specific classes. The menu item could be something like this:

- Rango
  - Add class to hintables
    - group-row
    - js-group-row
    - js-nav-to
    - js-boarditem
    - js-tap-hold-drag
    - js-tap-indication
    - ui-sortable-handle
  - Ignore class from hintables
      - group-row
      - js-group-row
      - js-nav-to
      - js-boarditem
      - js-tap-hold-drag
      - js-tap-indication
      - ui-sortable-handle

I'll have to see how complicated it is to implement something like this.

I have planned trying to reduce duplicates by looking up similar clickables in the vicinity. But you are right that this is a hard problem and the manual selector-based approach would be easier to implement.

I already had in mind using Element.matches() to simplify the logic of getting clickable elements. I think I did it the way it is now because at the beginning I wanted to know why elements were added to clickables for debugging purposes. I am in the middle of a big rewrite of the code to display hints related to issue #44 and I'm changing that function to just isClickable.

I like your solution for the overrides but I think we will need two different selectors fields: one for adding and one for ignoring. The thing is the default selectors would be very generic and having the user be able to delete those it's not gonna be very helpful. For example, I don't think users would want to delete `[role="button"]`, but having a way to ignore `div[role="button"].class-to-ignore` could instead be useful. When checking if an element is clickable I can just add the user defined selectors to the default ones and add the ones to ignore using `:not()`.

**Comment by david-tejada** [comment]
Now that I think of it, an issue with the context menu approach is that the element where the user clicks is not guaranteed to be the clickable element. It might be a span inside it or a wrapper or something like that. So maybe your idea of just letting the user enter the selector is going to be more appropriate.

**Comment by adam-coster** [comment]
Yep, it'll be hard to identify the thing the user clicked, and then hard again to know what it means for other elements to be "similar". I say "hard", but maybe even impossible?

I was thinking about forking the project to play around with the idea, if I can find the spare time, but didn't want to if it definitely wasn't a direction you'd be interested in.

**Comment by david-tejada** [comment]
Absolutely, go ahead. Any feedback is greatly appreciated.

**Comment by david-tejada** [comment]
I ended up implementing the automated solution, so it wasn't impossible 😁. I think the solution I came up with is even better than what I initially had in mind with the context menu. The user doesn't have to use the mouse at all. You can read about it in the [readme](https://github.com/david-tejada/rango#hints). I still want to add an option so the user can manually edit the selectors.

Regarding adding hints to headings, I tried coming up with a solution but I wasn't happy with it. I didn't want to have hints for things that aren't clickable. Then I tried to add a behavior so that if the user clicks a heading that is not clickable it would scroll to the top but it was messy. Sometimes the heading wouldn't be a heading and more like a title for a media component or something similar. Other times the heading would have a clickable element within it so I would need to check for that. Anyway, the bottom line is I couldn't find a satisfying solution that wasn't overly complicated and confusing.

A different solution that could work could be to add a command like `crown text <text>`. This would scroll to the top the first element (probably just heading or paragraph) that contains that text. So for example, saying something like `crown text different solution` would scroll this paragraph to the top. Maybe another command `crown next` could be useful, in case the text appears multiple times. Let me know what you think about this.

I'm going to close this issue for now. Feel free to open another one for the headings issue. If you want you can comment here any issues you have with custom hints or reach out in Slack.
